### ISSUE TITLE
CvUnit::validateCargoUnits() remove debugging code?

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#114]
This looks like code for debugging some problem, not something we should keep in the code base. Recalc modifiers should fix any problems with changes here, in fact it looks like all SM stuff is recalculated on every load.

@Thunderbrd ?

**Comment by Thunderbrd** [comment]
The cargo unit tracking is off for some reason.  I don't know how it goes off or when or why.  I'm not certain that a recalc would even address that in the least since recalculating doesn't affect much to do with units.  It may attempt to recalculate things with the SM stuff on load, as you say, for the sake of knowing things go out of whack, but I have never been able to trace down HOW this actually happens.  I might be able to now with some of the watch methods you've shown me.

**Comment by MattOttawa** [comment]
Looks like more old debug code that we might not need in FFreeListTrashArray and FFreeListArray:

	int getCorruptedAdjustment() const { return m_iCorruptedAdjustment; }
	void setCorruptedAdjustment(int iNewValue) { m_iCorruptedAdjustment = iNewValue; }
