### ISSUE TITLE
Assert about gold overflow related to GREATER_COMMERCE_SWITCH_POINT

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#115]
What is this `GREATER_COMMERCE_SWITCH_POINT`?

Certainly at 1000000 it is nowhere close to overflowing 32 bit int.

CvPlayerAI.cpp 5183

**Comment by raxo2222** [comment]
Civ4 int is 100x regular int when it comes to this stuff.
So overflow is at ~20 000 000, not ~2 000 000 000 just like in normal int.

**Comment by billw2012** [comment]
![image](https://user-images.githubusercontent.com/1453936/64479592-2fa0e180-d1b1-11e9-8856-949827eb5694.png)

Here is the code, I can't tell if this assert is valid here or not. This code doesn't actually modify the current gold, and it doesn't appear to be doing x100 calculations, so I can't see where it will overflow. However probably it can be looked at closer at some point, to see.

**Comment by Thunderbrd** [comment]
1 million isn't close to overflowing but there are two two digit granularity steps in there (mult by 100 then later divide by 100) that make it so around 2 million you'll start overflowing.  I set this up as a global so that if my math is far enough off that it can later be redefined what a 'greater' amount actually is.  It was later pointed out that the limit of a million millions is even less than that of a long long but I didn't get that impression when I was working with this because it WAS a long long when it was still overflowing - and I might not have gotten the right impression as to exactly where and why it was overflowing so this reaction, thinking it was an improvement, was not the appropriate one apparently.

However... I wasn't giving it quite as much care to study all the angles on this issue as I should have and a part of me recognized this at the time but figured that if we wanted to put the greater commerce switch point value out to some easily divisible by 100k amount within the span of a long long and make the greater commerce storage itself a long long then we would effectively have such a nearly infinite amount of potential storage that even the latest eras of the game could be reached without error so I was setting this up to make a huge amount of additional scaling possible, assuming long long may even itself not be enough eventually.

A value that represented Millions was easy for the player to cognize as a second category of tracking rather than asking them to track 10 or 20 million increments for each greater commerce amount which is why I made the greater amount 1 million.

If you guys want to go another way with that, cool, but keep in mind that the python and iconography is setup to handle things in this manner so that method of massively increased scaleability is there and available for easier modification into that level if we need it.
