### ISSUE TITLE
Assert: route cost is 0

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#121]
Not sure if this is correct or not. fromRoute type is rail and has a movement cost of 0. Not sure what route change is.
This is a frequent assert though.
CvPlot.cpp 5116

![image](https://user-images.githubusercontent.com/1453936/64480064-bc02d280-d1b8-11e9-843d-faae93b37ab6.png)

**Comment by alberts2** [comment]
A zero or negative route movement cost is definitely invalid. Some random events can lead to negative values from `getRouteChange`.

**Comment by billw2012** [comment]
The only way I see to reconcile those two statements is to simply cap the route cost at a minimum of 1. Is that correct?

**Comment by alberts2** [comment]
Yes and find out why these random events don't work correctly.

**Comment by billw2012** [comment]
Ah I thought you meant the events were intended to do that. If they are not meant to drop getRouteChange below zero, then I shouldn't cap the route cost (thus hiding the problem even though it is still there), but instead leave the assert and fix the underlying bug.

**Comment by alberts2** [comment]
For some reason some events get executed multiple times and that leads to things like negative movement costs.

**Comment by alberts2** [comment]
Here another case of negative movement cost:
https://forums.civfanatics.com/threads/single-player-bugs-and-crashes-v39-plus-svn-after-the-20th-of-july-2019.647928/page-49#post-15532833

**Comment by Toffer90** [comment]
I think recalc apply the tech modifier to ROUTE_MODERN_ROAD (Highway) without first resetting the current value to zero.
If it did reset it to zero then that means a recalc would always fix the bug if the bug was that events that should only trigger once triggered multiple times.
Only highways are modified by events, so it wouldn't explain why rails have less than 1 cost,
Only highways are modified by techs in xml, so the recalc bug I mentioned wouldn't explain the rails either.

See https://forums.civfanatics.com/threads/i-want-to-help-this-mod.572368/page-18#post-15555285

**Comment by raxo2222** [comment]
Maybe railways are affected by base game events?
That is there may be vanilla events, that aren't "duplicated" in mod.
