### ISSUE TITLE
Windows 7 crashes

### ISSUE THREAD

**Issue by MattOttawa** [caveman2cosmos/Caveman2Cosmos#1275]
Sometimes changes work on my computer and crashes on raxos.
Some investigation might help to avoid this problem in the future.

https://github.com/caveman2cosmos/Caveman2Cosmos/pull/1270/files

**Comment by MattOttawa** [comment]
Apparently adding a bit of unused code can crash windows 7?https://github.com/caveman2cosmos/Caveman2Cosmos/commit/ed30cdcc77b582229c4446266bdc527bf9a082ce

**Comment by raxo2222** [comment]
Yes, no idea why it was crashing with that, now its solid as rock

**Comment by MattOttawa** [comment]
post a mini dump next time if you get one please.
Or better yet - attach the VS debugger and post screen shots.

**Comment by Toffer90** [comment]
Yeah, since you're the only dev with windows 7, it might be practical if you learn how to attach VS to C2C.

Just install base VS community, barebone install (no components selected), and open "...\Sources\C2C" (VS2019).sln" with it.
It will tell you to install at least one component. After that you just need to select x86 in the dropdown box where it says "any CPU", the dropbox is displayed close to VS toolbar at the top.
After that you simply hit the green play button, and VS will launch the game.

**Comment by MattOttawa** [comment]
art info enums part 1 #1303

**Comment by raxo2222** [comment]
Didn't get crashes from it so its all good

**Comment by MattOttawa** [comment]
#1316

**Comment by raxo2222** [comment]
No crashes here

**Comment by MattOttawa** [comment]
#1317

**Comment by raxo2222** [comment]
No problems here
