### ISSUE TITLE
Too much "<building> has ceased doing business." spam when changing civics.

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#135]
Instead we should just say what active classes have stopped, or highlight them all at once with one message or something.

![image](https://user-images.githubusercontent.com/1453936/64492595-75bb7b00-d26d-11e9-9188-94943fb95372.png)
(imagine this but 10 pages of it)

**Comment by Thunderbrd** [comment]
The message is being triggered exactly when the code realizes the building has been disabled, in each city.  I think we would need a bool (by building so perhaps a struct vector) in CvPlayer that stores the building that's been messaged so that the message can be given only once (more generically than to call out the exact city that the disabling has taken place) and then when it encounters the disabling event in the next city it checks first to ensure that the building isn't included in the vector list of disabled buildings messaged that round.  If it's not on the list, it adds it to the list and sends the message and if it's on the list then it just skips that bit.  Then in doTurn for the player, clear the list, so that round by round it's only tracking the notification once.  Now, it's possible for a building to be enabled and disabled in the same round or vice versa, so perhaps the struct needs to include a bool for which has been used and that needs to be stored and checked as well (bChange).
