### ISSUE TITLE
Add check for out of date UserSettings dir

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#141]
We should do this for v40, so people upgrading from v39 are not ALL asking why they can't build stuff.

**Comment by raxo2222** [comment]
Mod won't load if it isn't named exactly "Caveman2Cosmos", or if it's located in My Documents too.
Maybe it is possible to do these checks very early, just like its done with FPK live?

**Comment by billw2012** [comment]
Definitely we can check the directories easily. Can we version check UserSettings just by looking for a specific file or something? We can rename the directory to UserSettings_old or something.

**Comment by raxo2222** [comment]
@Toffer90 may know

**Comment by Thunderbrd** [comment]
It would be very nice to be able to fix whatever the issue is with the mod folder requiring the exact Caveman2Cosmos name.  I know that it's better for debugging if it requires that naming, sure, BUT if we want to play an online ongoing MP game again, it would be helpful if we could maintain another mod folder for that with its own unique name and it sounds like right now that would be impossible.  Any hope of fixing that?

**Comment by billw2012** [comment]
I think the problem is we rely on relative pathing to reach assets of the base game. I don't know if we can do path resolution ourselves before the game loads assets referenced in the themes etc, maybe @Toffer90 knows about it. If we can intercept those paths then we can resolve the paths our selves to where ever we need them to be.

**Comment by billw2012** [comment]
Was fixed already.
