### ISSUE TITLE
Autoplay AI doesn't play current round, only next one

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#150]
See here https://forums.civfanatics.com/threads/paging-system-v2.649681/#post-15545342

Probably this is fairly straight forward in that the current round is already in progress and thus its too late for AI code path to execute. Might need to have special case handling for current round starting AI play.

**Comment by Thunderbrd** [comment]
Cool!  I won't pretend to have a deep enough grasp of the order of AI being triggered to make decisions comes in enough to have a hope of solving this so it's neat to see you add this to the list of things to look into because it would be very helpful for testing to be able to tell the AI to automate in small round increments without it hindering their play.  Evaluating each round of choices by direct observation in-game could really help with AI diagnosis at times.
