### ISSUE TITLE
caveman2cosmos license?

### ISSUE THREAD

**Issue by gentooza** [caveman2cosmos/Caveman2Cosmos#152]
Hi!

thanks for this amazing mod, I've just found the project code repository.

I see no license at all? is then caveman2cosmos closed source (and artwork)?
https://www.gnu.org/licenses/license-list.html#NoLicense

cheers

**Comment by alberts2** [comment]
The rights for Civilization 4, the source code and artwork from the original game which Caveman2Cosmos uses belong to Firaxis and 2k Games.

**Comment by gentooza** [comment]
ok,

Thanks for your answer. Perhaps would be nicer (and correct) to have some kind of EULA or license clarification in the repository. 

Also the copyright statement, moreover if you are being helped by a community of developers in their spare time.

cheers!

**Comment by billw2012** [comment]
Re-opened, we should have a license in the repository root ideally. Probably GPL is safest for compatibility, we want to allow explicitly derivative mods (would be pretty cheeky not to given the mods heritage).
Also a list of integrated mods in the root would be nice as well, with author names.

**Comment by alberts2** [comment]
We can't just put the mod under GPL or any other license. You should read the EULA you accepted when installing the game:
`USER CREATED CONTENT: The Software may allow you to create content, including but not limited to a gameplay map, a scenario, screenshot of a car design or a video of your game play. In exchange for use of the Software, and to the extent that your contributions through use of the Software give rise to any copyright interest, you hereby grant Licensor an exclusive, perpetual, irrevocable, fully transferable and sub-licensable worldwide right and license to use your contributions in any way and for any purpose in connection with the Software and related goods and services, including the rights to reproduce, copy, adapt, modify, perform, display, publish, broadcast, transmit, or otherwise communicate to the public by any means whether now known or unknown and distribute your contributions without any further notice or compensation to you of any kind for the whole duration of protection granted to intellectual property rights by applicable laws and international conventions. You hereby waive any moral rights of paternity, publication, reputation, or attribution with respect to Licensor&#8217;s and other players&#8217; use and enjoyment of such assets in connection with the Software and related goods and services under applicable law. This license grant to Licensor, and the above waiver of any applicable moral rights, survives any termination of this License.`

That basicly means that we don't have any rights and Take2Games owns the rights for all user created content.

**Comment by billw2012** [comment]
I don't think this applies, we aren't *using* civ to create the content (which is implied by "The Software may allow you to create"), we are creating content *for* civ. This might apply for instance to scenarios created in the world builder, but doesn't apply to stuff we make outside the game.

**Comment by gentooza** [comment]
Hi!

thanks for thinking about it.
(if I can give my opinion here :-D )
I agree @billw2012 , I guess maps made with world builder or in game screenshots are property of Firaxis (or whoever has the Civilization franchise now)
But your code is simply C++ source code compiled against some dynamic closed source .dll libraries, so you should be able to license your source code as you want. 
* the easiest could be a non copyleft license: MIT, BSD, Apache, etc. but it permits 3th party to close it.
* Also you can use GPL+ license and use a linking exception, to be able to link code with Civilization dlls.
https://en.wikipedia.org/wiki/GPL_linking_exception

For a good source code licensing practises I'd recommend GNU savannah guidelines:
https://savannah.gnu.org/maintenance/HowToGetYourProjectApprovedQuickly/

Also, perhaps,  you need a complete list of collaborators, and they have to give explicit permission to license their work under the chosen license.

I can help whatever you need.

cheers!

**Comment by alberts2** [comment]
> But your code is simply C++ source code compiled against some dynamic closed source .dll libraries, so you should be able to license your source code as you want.

But that source code is only a modified version of the original game code. The same goes for some graphic assets and there are also assets from other games in this mod.

What license would cover that situation?

**Comment by gentooza** [comment]
> > But your code is simply C++ source code compiled against some dynamic closed source .dll libraries, so you should be able to license your source code as you want.
> 
> But that source code is only a modified version of the original game code. The same goes for some graphic assets and there are also assets from other games in this mod.
> 
> What license would cover that situation?

ok, so:

+ source code is derived from previous work, where is stored this previous source code? is it cover under any source code license?
+ Have you got any own graphic assets? which tools did you need to make them?
+ Are you using external graphics assets from other mods or games? Are they public? which license they use?
+ Also I know caveman2cosmos uses other mods together, are they separated in code? dynamic linked? which license they have?

surely it's hard, but a good start should be identify caveman2cosmos original work, other mods work, and civilization work in repository, I think.

at worst, you'll have to rewrite/remake some components in the mod if you are still interested in make it open source.

cheers

**Comment by billw2012** [comment]
Yeah I don't think anyone is motivated to do that at the moment! I just want to keep this issue open because we should work it out sometime. Either we don't want anyone forking this and releasing their own versions, or we do, but we should be explicit either way.

**Comment by gentooza** [comment]
Yeah, I guess it's a little bit a titanic issue.
If you have time and motivation to spend here, I'll help the best I can

cheers!
