### ISSUE TITLE
Add Python linting to AppVeyor.

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#22]
Run it for Python changes only

**Comment by billw2012** [comment]
http://pylint.pycqa.org/en/latest/user_guide/run.html
https://github.com/PyCQA/pylint

**Comment by trym-b** [comment]
Hi

I thought I might help out with this issue but I need some feedback in order to contribute to this issue.

`pylint` has dropped support for `python 2` since version [2.0](https://pylint.pycqa.org/en/latest/whatsnew/2.0.html), so the latest versions of `pylint` will most likely not run very well on `python 2` code. It is unclear to me if this code base is transitioning to `python 3` or if it is stuck with `python 2`. Right now it looks like both `python 2` and `python 3` is used by this project.

Here are some of the potential solutions:

1. Run `pylint` version 1.9 on all `*.py` files.
    Advantage: No special handling for `python 2` or `python 3` files.
    Drawback: Updates to `pylint` will never introduce new warnings, `pylint` might get confused if `python 3` files are used by `python 2` files and vice versa 
2. Run `pylint` version 1.9.0 on all `python 2` files
    Advantage: Relatively simple to set up
    Drawback: `python 3` files are ignored, requires a list of all `python 3` files to ignore
3. Run `pylint` version 2.6.0 or newer on all `python 3` files
    Advantage: Relatively simple to set up
    Drawback: `python 2` files are ignored, requires a list of all `python 2` files to ignore
4. Run `pylint` version 2.6.0 (latest version) or newer on all `python 3` files, while run 1.9.0 on all `python 2` files.
    Advantage: Best of both worlds
    Drawback: Requires a list of files of all `python 3` or all `python 2` files. Requires 2 different configuration files for `pylint`

Let me know which (if any) of the solutions above is OK for you.

**Comment by MattOttawa** [comment]
I think we are stuck at python 2 for now. Any python 3 stuff is probly scripts not run by the game.
If you could cover all the stuff in the Python folder and the Private Maps folder that would be great.
That'll be all the in game stuff which should be python2.
