### ISSUE TITLE
Overflow in various calculations, particularly population

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#240]

**Comment by Thunderbrd** [comment]
There's also a mean little one in late stage combats when strength values get too high.  This will be a crippler for late stage games on SM.  I've known about it for a while but haven't figured out what I need to do with it yet because it involves combat strength that gets reported to the exe.

**Comment by KaTiON-PT** [comment]
Would it be possible to use the same classes that the treasury uses to handle large numbers?

**Comment by Thunderbrd** [comment]
In the case of the combats I'm not sure - I'm not sure how or why the exe needs the strengths reported to it in the first place.  Generally though, I've been corrected on my thinking that the 'greater' int would be anywhere better than a long long type assignment.  Problem is for the combat values, the exe wants an int.  If this is a superflous check for the exe and doesn't really screw anything up then sure, a 'greater' strength int for the total might help, or the problem is that the granularity is being applied in too many layers at once and shouldn't need to be considered out to 4 or even 6 decimals.  It's overflowing out when strengths are going over 1k or so, maybe a bit higher, after all % mods so something might be correctable in the math itself as well.  It's also hard to get a combat eval of str vs str when those str numbers are broken into 2 ints.  I'm not sure what the best approach is or where it actually overflows yet either so more investigation is needed.

Why population is overflowing is also mysterious... could it be the food thresholds that are overflowing rather than the populations themselves?

**Comment by KaTiON-PT** [comment]
> Why population is overflowing is also mysterious... could it be the food thresholds that are overflowing rather than the populations themselves?

By population I think Billw is refering to the total population value shown in city screen when you hover your pop number, as well as the sum of all that shows in your demographics screeb. Neither can surpass 2,147,483,647.

**Comment by Thunderbrd** [comment]
The first can't I don't think because it's not based on a formula but an established chart... maybe.  I could be wrong.  It needs to be adjusted anyhow once we do the Nomadic bit further so we have a better idea of what the amount is supposed to be per pop.  National totals would definitely be overflowing I'm sure.  So yeah, there's that - and then chaos ensues.  That's expressed through python screens so can it even be made a long long and transfer to python?

**Comment by MattOttawa** [comment]
Some overflows have been fixed.
New issues can be made for any overflows that are still possible.
Research is one spot that is not fixed yet, and it has it's own issue already.
