### ISSUE TITLE
Mapscripts crash or produce python errors.

### ISSUE THREAD

**Issue by raxo2222** [caveman2cosmos/Caveman2Cosmos#272]
I'm generating those on Duel size with default map settings.

Crash: Arboria, Archipelago, Big and Small, Continents, Custom Continents, Donut, Fractal, Full of Resources, Global Highlands, Hemispheres....
Python error on start: Balanced

It seems that only World, Tilted Axis mapscript doesn't crash.

**Comment by billw2012** [comment]
No problems for me with arboria or balanced, I make new maps all the time for testing. 
There was a problem a week ago when I first committed the Python interface changes, but I fixed it straight away.

**Comment by billw2012** [comment]
Oh yeah you are on Win 7, I will test that...

**Comment by Toffer90** [comment]
I'm guessing world doesn't crash as world never asks the dll to do any of the work, and that the crashpoint probably is in the dll whcich has seen some big technical modification on the dll to python interface lately,
Most other mapscripts delegates a lot of the map generation jobs to generic dll code instead of having unique code for it. Strange that Perfect Mongoose crash though, as it has unique code for mostly everything too.

**Comment by raxo2222** [comment]
This one was fixed
