### ISSUE TITLE
No unit is selected on new game start

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#32]
No reason we couldn't also select a unit on loading from a save where not all units have moved either I think? That always bugged me.

**Comment by Thunderbrd** [comment]
yeah these drive me nuts but I've not figured out where to put this kind of thing in the code and what function call to make to do it.  Would take a little study to determine how this is done but I get lost trying to figure it out because it happens during a lot of weaving in and out of the exe during a normal round procedure.

**Comment by dzfischer** [comment]
Seems to be fixed in current version; an active unit is selected on game load, and game start selects the Ancestral Band.

**Comment by Toffer90** [comment]
> Seems to be fixed in current version; an active unit is selected on game load, and game start selects the Ancestral Band.

Yeah, I fixed this one some months ago. The issue still happens if the recalc window pop up when the game is ready; didn't figure out why that broke things, but I figured it was a meh, recalc is a nice to have and it is not often it pops up for the mainstream player anyhow.
