### ISSUE TITLE
Barbarians should be upgraded for the terrain they spawn on

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#34]
Avoiding them dying to terrain damage.

**Comment by Thunderbrd** [comment]
There are promos for that.  If we could generate a gamewide tracking of which promotion applies to which terrain then this could be done in a way that isn't nearly as time-costly as creating another loop through all promotions every time a barb spawns.  Not sure of the best method to set that up so some advice would be good on that.  Would this also apply to units barbs build in cities?

**Comment by Toffer90** [comment]
I prefer it the way it currently is, that barbarians follow the same game rules in this regard as any other player.

Barbarian invasion stacks should learn how to navigate around large terrain damage areas; the same could be said about regular AI players too.

That there's some random hostiles weakened in a desert or a tundra is just flavour to the game imo.

**Comment by Thunderbrd** [comment]
On large swaths of tundra or desert it could mean they don't have the option to even get far enough to have mattered to play enough to warrant being spawned.  Plus, there are some AI considerations that are simply hard to get advanced enough to be what you're asking for, though perhaps yes eventually it would be nice to figure out how to go about changing the AI pathing to consider 'better' ways to go to a target where terrains and features that damage lie between you and your target.  Problem is pathing is so far above my grade I wouldn't personally dare.  But I COULD do this... sooo... it's maybe worth considering for now.  Of course, I just play without the option because I find it annoying in the way it's currently designed, and AI problems with it are a part of that.
