### ISSUE TITLE
Improvement upgrade issues

### ISSUE THREAD

**Issue by raxo2222** [caveman2cosmos/Caveman2Cosmos#530]
Currently improvement upgrading is broken in three cases:
When improvement and its upgrade unlocks at same tech 
When upgrade is unlocked before improvement
When alternative upgrades are earlier than main upgrade

If Seasonal Camp or other improvement spawns resource that is incompatible with improvement then:
Improvement should autoupgrade to one providing this resource, or be marked somehow.

\<ImprovementUpgrade>IMPROVEMENT_COTTAGE\</ImprovementUpgrade>
			\<AlternativeImprovementUpgradeTypes>
				\<ImprovementType>IMPROVEMENT_SCAVENGING_CAMP\</ImprovementType>
				\<ImprovementType>IMPROVEMENT_FRUIT_GATHERING_CAMP\</ImprovementType>
				\<ImprovementType>IMPROVEMENT_PLANT_GATHERING_CAMP\</ImprovementType>
				\<ImprovementType>IMPROVEMENT_SEED_CAMP\</ImprovementType>
				\<ImprovementType>IMPROVEMENT_MUSHROOM_GATHERER\</ImprovementType>
				\<ImprovementType>IMPROVEMENT_GRAPE_GATHERING_CAMP\</ImprovementType>
				\<ImprovementType>IMPROVEMENT_SILK_FARM\</ImprovementType>
				\<ImprovementType>IMPROVEMENT_WOOD_GATHERER\</ImprovementType>
				\<ImprovementType>IMPROVEMENT_STONE_TOOLS_WORKSHOP\</ImprovementType>
				\<ImprovementType>IMPROVEMENT_SALT_GATHERER\</ImprovementType>
				\<ImprovementType>IMPROVEMENT_TAR_GATHERER\</ImprovementType>
			\</AlternativeImprovementUpgradeTypes>

**Comment by Thunderbrd** [comment]
I wrote a guide to the improvement upgrade system a while back.  It should be something you can search for as you go through pages on the forum.  I think I included the rules on what you can and cannot do with it.  Some of the things you call broken were just accepted details in the design.  Alt upgrades should never be able to unlock before the primary, that sort of thing.  How is an upgrade unlocked before an improvement?  I don't understand what you're trying to say there?  It also wasn't really designed to account for upgrades being available at the same tech - you'd basically want to use your workers to either do one or the other at that point.  An improvement shouldn't improve to another improvement unless it is a 'better' one than the original.  If it's 'better' and both were available, then one should be chosen over the other, and if this happens because a resource is revealed, then workers should have to respond to change the improvement rather than the upgrade system responding.

**Comment by raxo2222** [comment]
Lumberjack - alternative upgrade of Fruit/Plant picking camp are unlocked on same tech - Sedentary Lifestyle.
Also Orchard and Plantation are unlocked way after Lumbermill
So there are at least two violations of that design,

Also it looks like I can't use cottage as main improvement.

**Comment by raxo2222** [comment]
It appears it was intentional that:
Main upgrade is unlocked before any alternative upgrade.
Main upgrade can be unlocked at same point as alternatives, when there are no or minimum overlaps between improvements.
Improvement is unlocked before any its upgrades.
