### ISSUE TITLE
Graphical glitch in tech tooltip

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#58]
Probably a formatter broken.

https://forums.civfanatics.com/threads/single-player-bugs-and-crashes-v39-plus-svn-after-the-20th-of-july-2019.647928/page-46#post-15530822

**Comment by billw2012** [comment]
It happens on in progress game, but not in new game. Happens on SVN latest as well, so not something that happened since moving to git.

**Comment by raxo2222** [comment]
On Discord we found out, that it always happens if you set all tech cost modifiers to 100:
Noble or higher handicap (lower than Noble  reduce cost of tech for player)
Normal Game Speed
Changing TECH_COST_MODIFIER to 100 in global defines
Changing <iResearchPercent> to 100 for Classical era (Floristry tech is here).

In this case bug disappears if you change Floristry name to something else, or just add space on beginning/end.

**Comment by Toffer90** [comment]
This bug is utterly weird...

**Comment by raxo2222** [comment]
I wonder if it is case, where [coverity ](https://scan.coverity.com/projects/caveman2cosmos-caveman2cosmos?tab=overview) reported memory corruption.

**Comment by raxo2222** [comment]
This one was fixed - we never knew, if it was something that coverity reported, or it was bug in python - python tech tree display was revised.
