### ISSUE TITLE
Organize / Cleanup of Modules

### ISSUE THREAD

**Issue by dzfischer** [caveman2cosmos/Caveman2Cosmos#774]
There are a number of modules which are either unfinished (Mine Warfare, etc) or important enough to warrant moving directly into core for easier manipulation / significantly reduced hassle when editing (much of DH's animal content, Natural Wonders, etc), right alongside modules that actually warrant the module status (Alt-Timelines, Cusomt_*, etc).

First these should be sorted out by an experienced dev (@Thunderbrd maybe?) - making a README.txt file in each module with its status would help users who want to use the module system, probably best solution - and then someone else can disable or import into core as necessary.

**Comment by Thunderbrd** [comment]
It would be good for me to have the unit plans completed before trying to get into this further.  I may along the way find some I want included.  Some of these divisions are just in part there to separate out various projects as well.  I do know that one 'mistake' in the unit core is to have the Hashishin moved to the core rather than in its own module because it is in a way a cultural unit, or at least not technically a core one since it stems from a special wonder.  I haven't seen too many problems with what is or what is not core - though I'd probably prefer neanders to be in a module just to separate them into their own project file.  It's true that in some ways its easier to have everything in core, but in other ways its also useful to have some stuff split into its own by theme so that you can work on the core stuff as a basis for establishing design principles underlying all other choices for more addendum or 'project' style content.

**Comment by Thunderbrd** [comment]
Of course, another way we can do things is to use multiple files IN the core for some of those divisions.  Much as we have with bonus files by category.

**Comment by Thunderbrd** [comment]
I'd REALLY like to split units into land/naval/air files also.

**Comment by dzfischer** [comment]
> Of course, another way we can do things is to use multiple files IN the core for some of those divisions. Much as we have with bonus files by category.

This is probably the way to go. I'm currently editing some build actions in CIV4UnitInfos.xml, which is sixty-eight and a half **_thousand_** lines long. That ain't right.
